platform :ios, '13.0'
use_frameworks!
swift_version = "5.0"

inhibit_all_warnings!

workspace 'POPMVVM.xcworkspace'

def shared
    promiseKit
end

target 'POPMVVM' do
    project 'POPMVVM.xcodeproj'
    shared
    
    target 'POPMVVMTests' do
        inherit! :search_paths
    end
    
    target 'POPMVVMUITests' do
        inherit! :search_paths
    end
    
end

target 'WebAPI' do
    project 'WebAPI/WebAPI.xcodeproj'
    
    promiseKit
    
    target 'WebAPITests' do
        project 'WebAPI/WebAPI.xcodeproj'
        
    end
end


